"""
Crystal structure visualisation module for CrystaLyse.AI.

This module provides comprehensive visualisation capabilities for crystal structures
generated by the Chemeleon CSP tools. It supports multiple visualisation backends
including py3Dmol for interactive 3D web visualisations and Plotly for custom
plotting needs.

Classes:
    CrystalVisualiser: Main visualisation class with multiple backend support
    StructureStorage: File management and organisation for crystal structures
    
Functions:
    create_visualisation_report: Generate comprehensive HTML reports
    
Example:
    >>> from crystalyse.visualisation import CrystalVisualiser
    >>> viz = CrystalVisualiser(backend="py3dmol")
    >>> view = viz.visualise_structure("structure.cif")
    >>> html_report = viz.create_multi_structure_report(structures, "CaTiO3")
"""

from .crystal_viz import CrystalVisualiser
from .storage import StructureStorage

__all__ = ['CrystalVisualiser', 'StructureStorage']