version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: dev/docs/requirements.txt
    - method: pip
      path: .

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
