"""CrystaLyse project-root discovery and scaffolding.

A ``.crystalyse/`` directory marks a CrystaLyse project root, similar to how
``.git/`` marks a Git repository.  This module provides:

- ``find_crystalyse_root()`` — walk upward from *cwd* to find the marker.
- ``ensure_crystalyse_root()`` — find or create the marker directory.

The directory layout created by ``ensure_crystalyse_root`` is::

    .crystalyse/
    ├── config.toml          # project-level settings (created empty)
    ├── plans/               # plan-mode artefacts (PR 2)
    ├── runs/                # provenance run data
    └── .gitignore           # ignores runs/ and plans/latest.md symlink
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

#: Content for the ``.crystalyse/.gitignore`` written on first creation.
#: ``runs/`` contains ephemeral provenance data — not version-controlled.
#: ``plans/latest.md`` is a convenience symlink that changes every run.
#: ``plans/*.md`` is deliberately NOT ignored so plan files can be committed
#: for reproducibility.
_GITIGNORE_TEMPLATE = """\
# Auto-generated by CrystaLyse — see dev/crystalyse/config/workspace.py
runs/
plans/latest.md
agent/
"""

#: Subdirectories created inside a fresh ``.crystalyse/`` root.
_SCAFFOLD_DIRS = ["plans", "runs"]


def find_crystalyse_root(start: Path | None = None) -> Path | None:
    """Walk upward from *start* (default: cwd) looking for ``.crystalyse/``.

    Returns the **containing directory** (the project root), not the
    ``.crystalyse/`` directory itself.  Returns ``None`` if no marker is
    found before reaching the filesystem root.
    """
    current = (start or Path.cwd()).resolve()

    # Walk upward — stop at the filesystem root (parent == self).
    while True:
        candidate = current / ".crystalyse"
        if candidate.is_dir():
            return current
        parent = current.parent
        if parent == current:
            # Reached filesystem root without finding the marker.
            return None
        current = parent


def ensure_crystalyse_root(
    *,
    create_if_missing: bool = True,
    interactive: bool = True,
    base: Path | None = None,
) -> Path:
    """Return the project root, creating ``.crystalyse/`` if needed.

    Parameters
    ----------
    create_if_missing:
        If ``True`` (default) and no existing root is found, create the
        directory structure.  If ``False``, raise ``FileNotFoundError``.
    interactive:
        If ``True`` (default), prompt the user before creating.  If
        ``False``, create silently — suitable for non-interactive / CI
        runs (spec §4.5 acceptance criterion W7).
    base:
        Directory in which to create ``.crystalyse/`` when none is found.
        Defaults to the current working directory.

    Returns
    -------
    Path
        The project root directory (parent of ``.crystalyse/``).

    Raises
    ------
    FileNotFoundError
        If *create_if_missing* is ``False`` and no root is found.
    """
    root = find_crystalyse_root(start=base)
    if root is not None:
        return root

    if not create_if_missing:
        raise FileNotFoundError(
            "No .crystalyse/ directory found. Run 'crystalyse init' or pass create_if_missing=True."
        )

    target = (base or Path.cwd()).resolve()

    if interactive:
        # Lazy import to avoid pulling in Rich at module load.
        from rich.prompt import Confirm

        if not Confirm.ask(
            f"No .crystalyse/ directory found. Create one in [cyan]{target}[/cyan]?",
            default=True,
        ):
            raise FileNotFoundError("User declined to create .crystalyse/ directory.")

    return _scaffold_crystalyse_dir(target)


def _scaffold_crystalyse_dir(project_root: Path) -> Path:
    """Create the ``.crystalyse/`` directory tree and default files.

    Parameters
    ----------
    project_root:
        The directory that will *contain* ``.crystalyse/``.

    Returns
    -------
    Path
        *project_root* (for chaining convenience).
    """
    crystalyse_dir = project_root / ".crystalyse"
    crystalyse_dir.mkdir(parents=True, exist_ok=True)

    # Create subdirectories.
    for subdir in _SCAFFOLD_DIRS:
        (crystalyse_dir / subdir).mkdir(exist_ok=True)

    # Write .gitignore (only if it doesn't already exist — don't clobber).
    gitignore = crystalyse_dir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_GITIGNORE_TEMPLATE)

    # Write an empty config.toml if none exists.
    config_toml = crystalyse_dir / "config.toml"
    if not config_toml.exists():
        config_toml.write_text("# CrystaLyse project settings — see docs/configuration.md\n")

    logger.info("Created .crystalyse/ directory at %s", crystalyse_dir)
    return project_root
